### ISSUE TITLE
Doesnt work with language-latex2e

### ISSUE THREAD

**Issue by werunom** [hesstobi/atom-autocomplete-latex-references#4]
Just tested for [language-latex2e](https://github.com/Aerijo/language-latex2e); sadly, this is not working. Works fine if I disable that language and enable [language-latex](https://github.com/area/language-latex).

Bit surprised since you have mentioned in changelog that you have added the support for this language in version `0.3.1`.

**Comment by hesstobi** [comment]
Sorry i did not test the new version properly. Thank your for reporting this.
Actually this is an issue in the [ language-latex2e](https://github.com/Aerijo/language-latex2e) package. I already create an [issue](https://github.com/Aerijo/language-latex2e/issues/8) there.

**Comment by Aerijo** [comment]
Fixed

**Comment by werunom** [comment]
Works fine :) Thanks!
